### ISSUE TITLE
Project needs a README.md

### ISSUE THREAD

**Issue by guettli** [AnkitMItraOfficial/StackOverFlow-Clone#3]
The README should start with the "why?". Why was this project created, and why is it cool.

Then it should contain instructions how to install the project.

**Comment by AnkitMitraOfficial** [comment]
I think this issue is now solved!Should I close it?

**Comment by guettli** [comment]
Thank you. This looks much better now.

Please add some headings so that there are several small text blocks and not one long one.

Please check your grammar. You seem to prefer "," to "."  But two sentences are separated by a dot in englisch :-)

You can use grammarly to check your grammar.

I think this issue is not solved yet.

**Comment by guettli** [comment]
I cleaned it up yesterday. Not perfect yet. Please create a new ticket if something is missing.
